---
- name:  Install Apigee hybrid on AWS EKS cluster
  hosts:  localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - aws-vars.yml

  collections:
  - bap_coe.bootstrap_runtime

  tasks:
  - name: Configure EKS kubectl access
    command: aws eks update-kubeconfig --region {{ REGION }} --name {{ CLUSTER_NAME }}