---
- name: Create AWS Users and Roles
  hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee-secure/credentials.yml
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-org-host-metadata.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-common-attributes.yml"
  - "{{ playbook_dir | dirname | dirname }}/resources/hybrid-region-dc-1.yml"
  - "{{ playbook_dir | dirname | dirname }}/aws-vars.yml"

  collections:
  - amazon.aws

  tasks:
  - name: Create a user and attach a managed policy using its ARN
    amazon.aws.iam_user:
      name: "{{ item }}"
      state: present
      access_key: "{{ AWS_ACCESS_KEY }}"
      secret_key: "{{ AWS_ACCESS_KEY_SECRET }}"
      managed_policies: "{{ managed_policies_list }}"
    with_items: "{{ aws_users }}"



