---
- name: Generate from templates
  hosts: localhost
  connection: local

  vars_files:
  - apigee-hybrid-workspace-build-variables.yml

  tasks:
    - name: Generate updated files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0777
      with_items: "{{ templates }}"

