---
- name: Build and push to artifact repository
  hosts: localhost
  connection: local

  vars_files:
  - apigee-hybrid-workspace-build-variables.yml

  collections:
  - commmunity.docker

  tasks:
    - name: Configure docker authentication
      shell: |
        gcloud auth configure-docker {{ repoLocation }}-docker.pkg.dev --project {{ PROJECT_ID }}

    - name: Create repository
      ignore_errors: true
      shell: |
        gcloud artifacts repositories create {{ repoName }} \
            --repository-format={{ repoFormat }} \
            --location={{ repoLocation }} \
            --description="Docker repository" \
            --project={{ PROJECT_ID }}

    - name: Push container to repo
      shell: |
       docker push {{ image_name }}:{{ tag }}
        

